settings:
  title: 'Status Page'
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 14 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: pooltools # unique identifier
    name: pooltools.net
    description: 'PoolTools.net homepage' # default=empty
    url: 'https://www.pooltools.net/index.php?cf-worker-status-page=1' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  - id: espnbottomline # unique identifier
    name: 'espn.com scores'
    description: 'ESPN.com bottomline scores feed' # default=empty
    url: 'http://www.espn.com/mens-college-basketball/bottomline/scores' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
  - id: mmmbrackets # unique identifier
    name: mmmbrackets.com
    description: 'MMMBrackets.com homepage' # default=empty
    url: 'https://www.mmmbrackets.com/index.php?cf-worker-status-page=1' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
